### ISSUE TITLE
Investigate broken `stg_ap_v_ret`

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#16]
Currently the MVP example works fine on Windows, but on Linux there is a high chance of broken `stg_ap_v_ret` which triggers a `barf` call. The bug is indeterministic; a successful build is seen at https://circleci.com/gh/tweag/asterius/1070.

**Comment by TerrorJack** [comment]
Another successful build at https://circleci.com/gh/tweag/asterius/1084, with tracing enabled. But I still got no clue about what's going on.

**Comment by TerrorJack** [comment]
A normal trace:

```
Entering stg_returnToStackTop
Entering stg_enter_ret
Entering Main_main_entry
Entering Main_main1_entry
Entering Main_zdwfact_entry
Entering Main_zdwfact_entry
Entering Main_zdwfact_entry
Entering Main_zdwfact_entry
Entering Main_zdwfact_entry
Entering Main_zdwfact_entry
Entering Main_.Lc33b
Entering Main_.Lc33b
Entering Main_.Lc33b
Entering Main_.Lc33b
Entering Main_.Lc33b
Entering Main_.Lc33H
120
Entering stg_stop_thread_ret
Entering StgReturn
```

An abnormal trace:

```
Entering stg_returnToStackTop
Entering stg_enter_ret
Entering stg_ap_v_ret
3
(node:21986) UnhandledPromiseRejectionWarning: RuntimeError: unreachable
    at wasm-function[21]:1362
    at wasm-function[62]:73
    at wasm-function[66]:112
    at wasm-function[34]:23
    at wasm-function[17]:11
    at WebAssembly.instantiate.then.i (/root/project/asterius/test/fact-dump/fact.js:1:34010)
(node:21986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21986) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So there's a high chance that the problem is not related with `stg_ap_v_ret` itself, but the entry function for the main closure is skipped in an unknown way. Still investigating.

**Comment by TerrorJack** [comment]
Just identified a potential stack corruption and pushed a fix in 95f60ae. Let's see if that helps.

**Comment by TerrorJack** [comment]
The fix is confirmed.

**Comment by TerrorJack** [comment]
Updated diagnosis:

Added basic-block level tracing on `wip-debug-via-indexed-rewrite` branch. Linux (broken) log:

```
Loading boot library store from "/home/terrorjack/asterius/.stack-work/install/x86_64-linux/ghc-8.5/8.5.20180413/share/x86_64-linux-ghc-8.5.20180413/asterius-0.0.1/.boot/asterius_lib/asterius_store"
Populating the store with builtin routines
Compiling test/fib/fib.hs to Cmm
Marshalling from Cmm to WebAssembly
Marshalling "Main" from Cmm to WebAssembly
Writing pretty-printed IR of Main to test/fib/Main.txt
Attempting to link into a standalone WebAssembly module
Writing linking report to "test/fib/fib.link.txt"
Invoking binaryen to marshal the WebAssembly module
Validating the WebAssembly module
Serializing the WebAssembly module to the binary form
Writing WebAssembly binary to "test/fib/fib.wasm"
Writing Node.js script to "test/fib/fib.js"
Using /usr/bin/node to run test/fib/fib.js
Entering main, Sp: 0, SpLim: 0, Hp: 0, HpLim: 0
Entering init_rts_asterius, Sp: 0, SpLim: 0, Hp: 0, HpLim: 0
Entering allocGroup, Sp: 0, SpLim: 0, Hp: 0, HpLim: 0
Setting local register 0 to 1048832
Entering allocGroup, Sp: 0, SpLim: 0, Hp: 0, HpLim: 0
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113536, HpLim: 3145728
Setting local register 1 to 2113536
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113600, HpLim: 3145728
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113664, HpLim: 3145728
Setting local register 2 to 2113664
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113736, HpLim: 3145728
Entering rts_evalIO, Sp: 0, SpLim: 0, Hp: 2113808, HpLim: 3145728
Entering createStrictIOThread, Sp: 0, SpLim: 0, Hp: 2113808, HpLim: 3145728
Entering createThread, Sp: 0, SpLim: 0, Hp: 2113808, HpLim: 3145728
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113808, HpLim: 3145728
Entering scheduleWaitThread, Sp: 0, SpLim: 0, Hp: 2179344, HpLim: 3145728
Entering StgRun, Sp: 0, SpLim: 0, Hp: 2179344, HpLim: 3145728
Entering stg_returnToStackTop, Sp: 0, SpLim: 0, Hp: 2179344, HpLim: 3145728
Branching to basic block 0, Sp: 0, SpLim: 0, Hp: 2179344, HpLim: 3145728
Setting local register 4 to 2113808
Setting local register 5 to 2113928
Setting local register 2 to 2097408
Setting local register 3 to 2179344
Setting local register 6 to 2113536
Setting local register 1 to 11
Entering stg_enter_ret, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 5, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 2 to 112
Branching to basic block 0, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 2, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 8
Branching to basic block 6, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 7, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 8, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 1 to 12
Entering stg_ap_v_ret, Sp: 2179320, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 0, Sp: 2179320, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 2, Sp: 2179320, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 8
Branching to basic block 32, Sp: 2179320, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 33, Sp: 2179320, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 34, Sp: 2179320, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 31, Sp: 2179320, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 4 to 1
Branching to basic block 24, Sp: 2179320, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 1 to 2
Branching to basic block 25, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 26, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 27, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 5 to 24
Branching to basic block 28, Sp: 2179328, SpLim: 2114120, Hp: 2179360, HpLim: 3145727
Setting local register 6 to 2179344
Setting local register 2 to 0
Branching to basic block 29, Sp: 2179328, SpLim: 2114120, Hp: 2179360, HpLim: 3145727
Branching to basic block 22, Sp: 2179328, SpLim: 2114120, Hp: 2179360, HpLim: 3145727
Setting local register 1 to 23
Branching to basic block 17, Sp: 2179336, SpLim: 2114120, Hp: 2179360, HpLim: 3145727
Setting local register 1 to 2
Branching to basic block 3, Sp: 2179336, SpLim: 2114120, Hp: 2179360, HpLim: 3145727
errBarf
(node:263) UnhandledPromiseRejectionWarning: RuntimeError: unreachable
    at wasm-function[16]:2047
    at wasm-function[41]:46
    at wasm-function[46]:118
    at wasm-function[26]:29
    at wasm-function[13]:17
    at WebAssembly.instantiate.then.r (/home/terrorjack/asterius/asterius/test/fib/fib.js:3:29234)
(node:263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Windows (working) log:

```
Loading boot library store from "C:\\Users\\astro\\haskell\\asterius\\.stack-work\\install\\be21b7a8\\share\\x86_64-windows-ghc-8.5.20180413\\asterius-0.0.1\\.boot\\asterius_lib\\asterius_store"
Populating the store with builtin routines
Compiling test/fib/fib.hs to Cmm
Marshalling from Cmm to WebAssembly
Marshalling "Main" from Cmm to WebAssembly
Writing pretty-printed IR of Main to test/fib\Main.txt
Attempting to link into a standalone WebAssembly module
Writing linking report to "test/fib/fib.link.txt"
Invoking binaryen to marshal the WebAssembly module
Validating the WebAssembly module
Serializing the WebAssembly module to the binary form
Writing WebAssembly binary to "test/fib/fib.wasm"
Writing Node.js script to "test/fib/fib.js"
Using C:\Program Files\nodejs\node.exe to run test/fib/fib.js
Entering main, Sp: 0, SpLim: 0, Hp: 0, HpLim: 0
Entering init_rts_asterius, Sp: 0, SpLim: 0, Hp: 0, HpLim: 0
Entering allocGroup, Sp: 0, SpLim: 0, Hp: 0, HpLim: 0
Setting local register 0 to 1048832
Entering allocGroup, Sp: 0, SpLim: 0, Hp: 0, HpLim: 0
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113536, HpLim: 3145728
Setting local register 1 to 2113536
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113600, HpLim: 3145728
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113664, HpLim: 3145728
Setting local register 2 to 2113664
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113736, HpLim: 3145728
Entering rts_evalIO, Sp: 0, SpLim: 0, Hp: 2113808, HpLim: 3145728
Entering createStrictIOThread, Sp: 0, SpLim: 0, Hp: 2113808, HpLim: 3145728
Entering createThread, Sp: 0, SpLim: 0, Hp: 2113808, HpLim: 3145728
Entering allocate, Sp: 0, SpLim: 0, Hp: 2113808, HpLim: 3145728
Entering scheduleWaitThread, Sp: 0, SpLim: 0, Hp: 2179344, HpLim: 3145728
Entering StgRun, Sp: 0, SpLim: 0, Hp: 2179344, HpLim: 3145728
Entering stg_returnToStackTop, Sp: 0, SpLim: 0, Hp: 2179344, HpLim: 3145728
Branching to basic block 0, Sp: 0, SpLim: 0, Hp: 2179344, HpLim: 3145728
Setting local register 5 to 2113808
Setting local register 2 to 2113928
Setting local register 3 to 2097408
Setting local register 6 to 2179344
Setting local register 4 to 2113536
Setting local register 1 to 11
Entering stg_enter_ret, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 5, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 88
Branching to basic block 0, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 2, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 2 to 8
Branching to basic block 6, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 7, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 8, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179304, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 1 to 12
Branching to basic block 3, Sp: 2179320, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 1 to 2
Entering Main_main_entry, Sp: 2179336, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 0, Sp: 2179336, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 1 to 58
Entering Main_main1_entry, Sp: 2179336, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 0, Sp: 2179336, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 2, Sp: 2179336, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 1 to 40
Entering Main_mainzuzdszdwgo_entry, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 3, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 5 to 0
Setting local register 4 to 1
Setting local register 2 to 0
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 1
Setting local register 5 to 1
Setting local register 4 to 1
Setting local register 2 to 1
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 2
Setting local register 5 to 1
Setting local register 4 to 2
Setting local register 2 to 2
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 3
Setting local register 5 to 2
Setting local register 4 to 3
Setting local register 2 to 3
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 5
Setting local register 5 to 3
Setting local register 4 to 5
Setting local register 2 to 4
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 8
Setting local register 5 to 5
Setting local register 4 to 8
Setting local register 2 to 5
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 13
Setting local register 5 to 8
Setting local register 4 to 13
Setting local register 2 to 6
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 21
Setting local register 5 to 13
Setting local register 4 to 21
Setting local register 2 to 7
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 34
Setting local register 5 to 21
Setting local register 4 to 34
Setting local register 2 to 8
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 55
Setting local register 5 to 34
Setting local register 4 to 55
Setting local register 2 to 9
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 1, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 3 to 89
Setting local register 5 to 55
Setting local register 4 to 89
Setting local register 2 to 10
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 2, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 1 to 46
Entering Main_.Lc2PG, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 0, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Entering print_int, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
55
Setting local register 1 to 23
Entering stg_stop_thread_ret, Sp: 2179336, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Branching to basic block 0, Sp: 2179336, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
Setting local register 2 to 2113808
Setting local register 3 to 2097408
Setting local register 1 to 56
Entering StgReturn, Sp: 2179328, SpLim: 2114120, Hp: 2179336, HpLim: 3145727
```

So it seems the magic does not happen in `stg_ap_v_ret`, by the time we branch into `stg_ap_v_ret`, the state of the whole system should be assumed to be inconsistent.

The problem is most likely related to `stg_enter_ret`. Given its notorious history of causing troubles (consider #10), a possible direction to fix the issue would be: recheck how we fixed #10, and revert that fix.

**Comment by TerrorJack** [comment]
Update: the revision that reverted the fix for #10 is in `wip-old-school-switch` branch, and it has seen one successful/one erroneous build.

**Comment by TerrorJack** [comment]
Something more magical is going on here.

I've implemented a conservational relooper to replace the default binaryen relooper in the `wip-no-relooper` branch. Now, there's about 2/3 chance of Linux tests directing skipping the main closure, 1/3 chance of diverging.

Possibilities listed below (they're not mutually exclusive):

1. The problem is in `stg_enter_ret`. We can probably force a "correct" version.
2. The problem lies somewhere else, and `stg_enter_ret` is already handed with an inconsistent system state.

Possible fixes:

1. Handle `stg_enter_ret` with extra care, probably pasting a "known to work" implementation generated from the Windows build.
2. Investigate even further.

**Comment by TerrorJack** [comment]
Still, no luck at locating the root cause. But I managed to implement a workaround and it landed in `master`: ship a blob of `AsteriusStore` that is known to work, and provide `--override-store` in `ahc-link` to use the shipped blob instead of the blob produced by `ahc-boot`.

**Comment by TerrorJack** [comment]
The root cause has been identified and fixed in `master`: improper use of `withSBS` and `withSV`. Switched to pool-based allocation when marshalling to `binaryen` for memory safety.
