### ISSUE TITLE
Missing rts cbits for `text`

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#357]
`Data.Text.Encoding` imports these functions for encoding/decoding:

* `_hs_text_decode_utf8`
* `_hs_text_decode_utf8_state`
* `_hs_text_decode_latin1`
* `_hs_text_encode_utf8`

This issue is blocking #347 #328 #257

**Comment by TerrorJack** [comment]
The easiest thing to do would be patching `Data.Text.Encoding` and avoiding ccalls at all. But let's see if we can fix vanilla `text` without too much trouble.

**Comment by TerrorJack** [comment]
Implemented and tested `_hs_text_decode_utf8` and `_hs_text_encode_utf8`, sufficient to unblock #347. Will leave this one open for some more time since the cbits stuff still needs more work.

**Comment by TerrorJack** [comment]
This still blocks #315:

```
file:///home/admin/asterius/asterius/test/diagrams/SquareLimit.mjs:4
process.on("unhandledRejection", err => { throw err; });
                                          ^

RuntimeError: RuntimeError: barf: _hs_text_decode_utf8_state
    at ExceptionHelper.barf (file:///home/admin/asterius/asterius/test/diagrams/rts.exception.mjs:143:13)
    at barf (wasm-function[7998]:0x2e7077)
    at textzm1zi2zi3zi1zmLZZOn9keu2Vl3XvFWCbVXmI_DataziTextziEncoding_.Lc2lfX (wasm-function[14173]:0x51d03d)
    at scheduleTSO (wasm-function[13906]:0x502579)
    at scheduleTSO_wrapper (wasm-function[13907]:0x5025c9)
    at Scheduler.scheduler_loop (file:///home/admin/asterius/asterius/test/diagrams/rts.scheduler.mjs:424:15)
    at file:///home/admin/asterius/asterius/test/diagrams/rts.scheduler.mjs:298:15
ahc-link: callProcess: node "--experimental-modules" "SquareLimit.mjs" (exit 1): failed
diagrams: callProcess: ahc-link "--input-hs" "test/diagrams/SquareLimit.hs" "--run" "--verbose-err" "--binaryen" (exit 1): failed
```
