### ISSUE TITLE
RuntimeError on using regex-pcre-builtin package

### ISSUE THREAD

**Issue by santhiya-v** [tweag/asterius#630]
**Description**

We are trying to convert an executable in duckling using austerius. It builds successfully after solving an issue mentioned [here](https://github.com/tweag/asterius/issues/610). When we try to run mjs file, we are getting runtime error which looks like originating from regex-pcre-builtin package methods

**Error**

JSException "RuntimeError: unreachable\n    at regexzmpcrezmbuiltinzm0zi95zi1zi2zi8zi43zmJ1sDX3M59fGEw4grsfXrCR_TextziRegexziPCREziWrap_.LcdzL (wasm-function[31156]:0x7590be)\n    at scheduleTSO (wasm-function[31301]:0x75f037)\n    at scheduleTSO_wrapper (wasm-function[31302]:0x75f064)\n    at Scheduler.tick (file:///duckling/install/rts.scheduler.mjs:346:22)\n    at Immediate.<anonymous> (file:///duckling/install/rts.scheduler.mjs:381:29)\n    at processImmediate (internal/timers.js:456:21)"

regex-pcre-builtin has native c code in it. Should we compile it with additional flags for such packages in ahc-cabal?

**Additional Info**

1. We are using the austerius lastest docker image
2. regex-pcre-builtin : https://hackage.haskell.org/package/regex-pcre-builtin
3. Duckling : https://github.com/facebook/duckling

**Comment by TerrorJack** [comment]
Unfortunately, we don't support C sources for now. In the longer term we'll have some degree of integration with existing toolchains (either `wasi-sdk` or `emscripten`), but for now the best thing to do would be to use pure Haskell regex library.

**Comment by janakg** [comment]
thanks, @TerrorJack, it looks like we do not have an easy option to convert all PCRE regex usage in the duckling library. Is there any workaround you could think for using a native C dependent libraries, as a pre-built binary or sth. Also, I couldn't find any Haskell implementation for PCRE. I am new to Haskell, any direction to solve this would be of great help.

**Comment by janakg** [comment]
@TerrorJack We are blocked on this issue. Can you give us some pointers to integrate native toolchain? We have experience with a few built systems, will give it a try for a PR.

**Comment by TerrorJack** [comment]
@janakg It may be possible to use another toolchain to cross-compile `pcre` to wasm, load the wasm files in js, and use JSFFI to call the exported functions in Haskell.

There's one problem with the approach though: it's hard to properly share the memory/table with the asterius universe, since the c functions will need to pass pointers when working with c strings. We'll look into this and come back with more detailed answer on how this may be done.

**Comment by janakg** [comment]
@TerrorJack thanks. This sounds like a viable option for now. I'll wait for your details.

**Comment by janakg** [comment]
Hi, Author of regex-pcre-builtin suggesting a similar solution as yours. Is there a way to take care of the c string references? thanks in advance.

https://github.com/stephen-riley/pcre2-wasm

**Comment by janakg** [comment]
Hi Did you get a chance to check this library, would it work?
https://github.com/stephen-riley/pcre2-wasm

**Comment by santhiya-v** [comment]
@TerrorJack Most of the dependent packages of duckling are having native c code but with only header files (.h). Will those packages also have problem in austerius ?

Example :
Text - https://github.com/haskell/text
ByteString - https://github.com/haskell/bytestring
Aeson - https://github.com/bos/aeson
etc.,
