### ISSUE TITLE
Usage of GHC.Conc.par leads to unreachable error

### ISSUE THREAD

**Issue by gkaracha** [tweag/asterius#653]
**Describe the bug**

During the development of https://github.com/tweag/asterius/issues/639, I noticed that the nofib test [`shootout/binary-trees`](https://gitlab.haskell.org/ghc/nofib/-/blob/master/shootout/binary-trees/Main.hs) fails with
```
Main: JSException "RuntimeError: unreachable    
    at wasm-function[108]:0x6e91    
    at wasm-function[4070]:0xd77de
    at wasm-function[4071]:0xd780b    
    at Scheduler.tick (file:///home/skull/tweag/asterius-alt/asterius/nofib/shootout/binary-trees/rts.scheduler.mjs:346:22)    
    at Immediate.<anonymous> (file:///home/skull/tweag/asterius-alt/asterius/nofib/shootout/binary-trees/rts.scheduler.mjs:381:29)    
    at processImmediate (internal/timers.js:456:21)"
```

After some tinkering I noticed that if I remove all invocations of `GHC.Conc.par` in the file, it executes as expected, so I think that this is the culprit.

**To Reproduce**
Download `Main.hs` from [here](https://gitlab.haskell.org/ghc/nofib/-/blob/master/shootout/binary-trees/Main.hs), build it with Asterius, and execute using node:
```
ahc-link  --ghc-option=-O2 --ghc-option=-Rghc-timing --ghc-option=-H32m --ghc-option=-rtsopts --ghc-option=-funbox-strict-fields --input-hs Main.hs
node Main.mjs 15 11
```

**Expected behavior**
The program should execute without errors. The expected stdout can be found [here](https://gitlab.haskell.org/ghc/nofib/-/blob/master/shootout/binary-trees/binary-trees.faststdout).

**Environment**
* OS name + version: Ubuntu 18.04.4 LTS (bionic)
* GHC version: 8.8.3
* Cabal version: 3.2.0.0
* Version of Asterius: 42d5be0b806211daf627aa6e16f65102bf3c06b0

**Comment by gkaracha** [comment]
Linking with `--verbose-err` gives a little more info:
```
Main: JSException "RuntimeError: barf: newSpark    
    at ExceptionHelper.barf (file:///home/skull/tweag/asterius-alt/asterius/nofib/shootout/binary-trees/rts.exception.mjs:147:13)    
    at barf (wasm-function[184]:0x9c55)    
    at Main_.Lr7z8_entry (wasm-function[108]:0x6eb7)    
    at scheduleTSO (wasm-function[4075]:0xd7aa5)    
    at scheduleTSO_wrapper (wasm-function[4076]:0xd7ad2)    
    at Scheduler.tick (file:///home/skull/tweag/asterius-alt/asterius/nofib/shootout/binary-trees/rts.scheduler.mjs:346:22)    
    at Immediate.<anonymous> (file:///home/skull/tweag/asterius-alt/asterius/nofib/shootout/binary-trees/rts.scheduler.mjs:381:29)    
    at processImmediate (internal/timers.js:456:21)"
```
