### ISSUE TITLE
Implementation of calloc is missing

### ISSUE THREAD

**Issue by gkaracha** [tweag/asterius#672]
**Describe the bug**

Asterius currently fails to compile test [codeGen/T15892.hs](https://github.com/tweag/asterius/blob/master/asterius/test/ghc-testsuite/codeGen/T15892.hs) from GHC's testsuite, giving the following error: 
```
T15892: JSException "RuntimeError: barf: calloc
    at ExceptionHelper.barf (file:///home/skull/tweag/asterius-alt/test-t15892/rts.exception.mjs:147:13)
    at barf (wasm-function[89]:0x4348)
    at Main_.Lr68r_entry (wasm-function[42]:0x3405)
    at scheduleTSO (wasm-function[2817]:0x954a8)
    at scheduleTSO_wrapper (wasm-function[2818]:0x954d5)
    at Scheduler.tick (file:///home/skull/tweag/asterius-alt/test-t15892/rts.scheduler.mjs:346:22)
    at Immediate.<anonymous> (file:///home/skull/tweag/asterius-alt/test-t15892/rts.scheduler.mjs:381:29)
    at processImmediate (internal/timers.js:456:21)"
```
This probably means that we have no working implementation of `calloc` for node to use.

**To Reproduce**
```
  ahc-link --verbose-err --input-hs T15892.hs
  node T15892.mjs
```

**Expected behavior**
The program should execute without errors.

**Environment**
* OS name + version: Ubuntu 18.04.4 LTS (bionic)
* GHC version: 8.8.3
* Cabal version: 3.2.0.0
* Version of Asterius: 013d008687f1c57accf4c5e29be05e73af1cabeb

**Comment by TerrorJack** [comment]
Since we have `malloc` implementation in #659, I can expect a simple `calloc` implementation which just calls `malloc` and then `memset`.
