### ISSUE TITLE
Implementation of (the math function) cos is missing

### ISSUE THREAD

**Issue by gkaracha** [tweag/asterius#673]
**Describe the bug**

Asterius currently fails to compile test [codeGen/cgrun035.hs](https://github.com/tweag/asterius/blob/master/asterius/test/ghc-testsuite/codeGen/cgrun035.hs) from GHC's testsuite, giving the following error:

```
cgrun035: JSException "RuntimeError: barf: cos
    at ExceptionHelper.barf (file:///home/skull/tweag/asterius-alt/test-cgrun035/rts.exception.mjs:147:13)
    at barf (wasm-function[67]:0x394b)
    at Main_.Lc4pf (wasm-function[35]:0x33eb)
    at scheduleTSO (wasm-function[3284]:0xace81)
    at scheduleTSO_wrapper (wasm-function[3285]:0xaceae)
    at Scheduler.tick (file:///home/skull/tweag/asterius-alt/test-cgrun035/rts.scheduler.mjs:346:22)
    at Immediate.<anonymous> (file:///home/skull/tweag/asterius-alt/test-cgrun035/rts.scheduler.mjs:381:29)
    at processImmediate (internal/timers.js:456:21)"
```
This probably means that we have no working implementation of `cos` for node to use.

**To Reproduce**
```
ahc-link --verbose-err --input-hs cgrun035.hs
node cgrun035.mjs
```

**Expected behavior**
The program should execute without errors.

**Environment**
* OS name + version: Ubuntu 18.04.4 LTS (bionic)
* GHC version: 8.8.3
* Cabal version: 3.2.0.0
* Version of Asterius: 013d008687f1c57accf4c5e29be05e73af1cabeb

**Comment by TerrorJack** [comment]
We have implementation for the triangular functions in Cmm primops in `Asterius.CodeGen`, but the C standard library interfaces aren't implemented. Before #658 gets implemented, I think we can add something like `Asterius.Builtins.Math` and implement these using the same logic in `Asterius.CodeGen`.
